spring:
  application:
    name: mian-cloud-api
  datasource:
    url: ${DB_URL}
    driverClassName: 'org.postgresql.Driver'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: env.properties
server:
  port: 8080

app:
  jwt-secret: ${JWT_KEY}
  jwt-expiration-min: 43200